// <auto-generated />
using IGP.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IGP.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20201125202503_migration_1.0.2")]
    partial class migration_102
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IGP.Models.Auth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auth");
                });

            modelBuilder.Entity("IGP.Models.Cargo", b =>
                {
                    b.Property<int>("CargoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CargoID");

                    b.ToTable("Cargo");

                    b.HasData(
                        new
                        {
                            CargoID = 1,
                            Nombre = "Gerente"
                        },
                        new
                        {
                            CargoID = 2,
                            Nombre = "Vendedor"
                        },
                        new
                        {
                            CargoID = 3,
                            Nombre = "Coordinador"
                        },
                        new
                        {
                            CargoID = 4,
                            Nombre = "SubGerente"
                        });
                });

            modelBuilder.Entity("IGP.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CargoID")
                        .HasColumnType("int");

                    b.Property<double>("DocIdentidad")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpleadoID");

                    b.HasIndex("CargoID");

                    b.ToTable("Empleado");

                    b.HasData(
                        new
                        {
                            EmpleadoID = 1,
                            Apellido = "Calambas",
                            CargoID = 1,
                            DocIdentidad = 1061732742.0,
                            Nombre = "Manuel"
                        },
                        new
                        {
                            EmpleadoID = 2,
                            Apellido = "Giraldo",
                            CargoID = 4,
                            DocIdentidad = 34319349.0,
                            Nombre = "Martha"
                        },
                        new
                        {
                            EmpleadoID = 3,
                            Apellido = "Bedoya",
                            CargoID = 2,
                            DocIdentidad = 1054765323.0,
                            Nombre = "Arturo"
                        },
                        new
                        {
                            EmpleadoID = 4,
                            Apellido = "Calambas",
                            CargoID = 3,
                            DocIdentidad = 34323432.0,
                            Nombre = "Alejandra"
                        });
                });

            modelBuilder.Entity("IGP.Models.Empleado", b =>
                {
                    b.HasOne("IGP.Models.Cargo", "Cargo")
                        .WithMany("Empleados")
                        .HasForeignKey("CargoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("IGP.Models.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
